version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server_mp
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: "P@ssw0rd1234"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - app_network


  backend:
    build: .
    container_name: node_backend_mp
    ports:
      - "3000:3000"
    environment:
      DB_SERVER: db
      DB_USER: sa
      DB_PASSWORD: "P@ssw0rd1234"
      DB_DATABASE: MPDatos
      DB_PORT: 1433
      PORT: 3000
    restart: always
    networks:
      - app_network

volumes:
  sql_data:

networks:
  app_network:
    driver: bridge
